# Generated by Django 5.1.3 on 2024-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_hall_location_student_points_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointshistory",
            name="points_type",
            field=models.CharField(
                choices=[("AUTO", "Автоматическое"), ("MANUAL", "Ручное")],
                default="AUTO",
                max_length=10,
            ),
        ),
    ]
