# Generated by Django 5.1.3 on 2024-12-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial_data'),
        ('leads', '0003_pointshistory_points_type'),
    ]

    operations = [
    ]
