# Generated by Django 5.1.3 on 2024-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_merge_20241204_1154"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["date", "status"], name="leads_booki_date_c7b899_idx"
            ),
        ),
    ]
