# Generated by Django 5.1.3 on 2024-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_booking_leads_booki_date_c7b899_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["time_slot"], name="leads_booki_time_sl_2c4f27_idx"
            ),
        ),
    ]
